"""initial schema

Revision ID: d0006ccb1308
Revises: 
Create Date: 2026-07-10 12:02:04.048371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0006ccb1308'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('bike_parking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('spot_count', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('PARACICLO', 'BICICLETARIO', name='parking_type'), nullable=False),
    sa.Column('operating_hours', sa.String(), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_bike_parking_geometry', 'bike_parking', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_bike_parking_source_id'), 'bike_parking', ['source_id'], unique=True)
    op.create_index(op.f('ix_bike_parking_type'), 'bike_parking', ['type'], unique=False)
    op.create_geospatial_table('bike_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('CICLOFAIXA', 'CICLOVIA', 'CICLORROTA', 'PASSEIO_COMPARTILHADO', name='route_category'), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=True),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('road_position', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('pavement', sa.String(), nullable=True),
    sa.Column('separation_element', sa.String(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.Column('neighborhoods', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('reference_year', sa.Integer(), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_bike_routes_geometry', 'bike_routes', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_bike_routes_category'), 'bike_routes', ['category'], unique=False)
    op.create_index('ix_bike_routes_neighborhoods', 'bike_routes', ['neighborhoods'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_bike_routes_source_id'), 'bike_routes', ['source_id'], unique=True)
    op.create_geospatial_table('bike_share_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('regional', sa.String(), nullable=True),
    sa.Column('inaugurated_at', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('EXISTENTE', 'EXISTENTE_3_0', name='station_status'), nullable=False),
    sa.Column('sponsor', sa.String(), nullable=True),
    sa.Column('current_slots', sa.Integer(), nullable=True),
    sa.Column('station_type', sa.String(), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_bike_share_stations_geometry', 'bike_share_stations', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_bike_share_stations_neighborhood'), 'bike_share_stations', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_bike_share_stations_source_id'), 'bike_share_stations', ['source_id'], unique=True)
    op.create_index(op.f('ix_bike_share_stations_status'), 'bike_share_stations', ['status'], unique=False)
    op.create_geospatial_table('leisure_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_leisure_routes_geometry', 'leisure_routes', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_leisure_routes_source_id'), 'leisure_routes', ['source_id'], unique=True)
    op.create_geospatial_table('rest_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_rest_points_geometry', 'rest_points', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_rest_points_source_id'), 'rest_points', ['source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rest_points_source_id'), table_name='rest_points')
    op.drop_geospatial_index('idx_rest_points_geometry', table_name='rest_points', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('rest_points')
    op.drop_index(op.f('ix_leisure_routes_source_id'), table_name='leisure_routes')
    op.drop_geospatial_index('idx_leisure_routes_geometry', table_name='leisure_routes', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('leisure_routes')
    op.drop_index(op.f('ix_bike_share_stations_status'), table_name='bike_share_stations')
    op.drop_index(op.f('ix_bike_share_stations_source_id'), table_name='bike_share_stations')
    op.drop_index(op.f('ix_bike_share_stations_neighborhood'), table_name='bike_share_stations')
    op.drop_geospatial_index('idx_bike_share_stations_geometry', table_name='bike_share_stations', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('bike_share_stations')
    op.drop_index(op.f('ix_bike_routes_source_id'), table_name='bike_routes')
    op.drop_index('ix_bike_routes_neighborhoods', table_name='bike_routes', postgresql_using='gin')
    op.drop_index(op.f('ix_bike_routes_category'), table_name='bike_routes')
    op.drop_geospatial_index('idx_bike_routes_geometry', table_name='bike_routes', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('bike_routes')
    op.drop_index(op.f('ix_bike_parking_type'), table_name='bike_parking')
    op.drop_index(op.f('ix_bike_parking_source_id'), table_name='bike_parking')
    op.drop_geospatial_index('idx_bike_parking_geometry', table_name='bike_parking', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('bike_parking')
    # ### end Alembic commands ###
